import { describe, it, expect, vi, beforeEach } from 'vitest';
const auth = vi.hoisted(() => ({ user: { id: 'auth-user', email: 'tech@example.invalid' } as { id: string; email: string } | null }));
vi.mock('../../../api/_auth', () => ({ requireUser: vi.fn(async (_req, res) => { if (!auth.user) res.status(401).json({ error: 'Unauthorized' }); return auth.user; }) }));
import handler from '../../../api/service-visits';
const pending = { id: 'j', contractorId: 'crew', status: 'new', scheduledDate: '2099-10-12', currentVisit: { id: 'j:visit:2', number: 2, approval: 'pending' } };
const response = () => { const res = { status: vi.fn(), json: vi.fn(), setHeader: vi.fn() }; res.status.mockReturnValue(res); res.json.mockReturnValue(res); return res; };
describe('server visit authority', () => {
  beforeEach(() => { auth.user = { id: 'auth-user', email: 'tech@example.invalid' }; vi.restoreAllMocks(); });
  it('rejects unauthenticated requests', async () => { auth.user = null; const r = response(); await handler({ method: 'POST', body: {} } as never, r as never); expect(r.status).toHaveBeenCalledWith(401); });
  it('rejects technician approval even when payload claims admin', async () => { const f = vi.spyOn(globalThis, 'fetch').mockResolvedValue(new Response('[{"role":"technician"}]')); const r = response(); await handler({ method: 'POST', body: { action: 'included', jobId: 'j', role: 'admin' } } as never, r as never); expect(r.status).toHaveBeenCalledWith(403); expect(f).toHaveBeenCalledTimes(1); });
  it('rejects unassigned contractors', async () => { vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(new Response('[{"role":"contractor"}]')).mockResolvedValueOnce(new Response(JSON.stringify([{ value: pending, updated_at: 'x' }]))).mockResolvedValueOnce(new Response(JSON.stringify([{ value: [{ id: 'other', status: 'approved', email: auth.user!.email }] }]))); const r = response(); await handler({ method: 'POST', body: { action: 'request', jobId: 'j' } } as never, r as never); expect(r.status).toHaveBeenCalledWith(403); });
  it('rejects concurrent mutation instead of overwriting another writer', async () => { const f = vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(new Response('[{"role":"admin"}]')).mockResolvedValueOnce(new Response(JSON.stringify([{ value: pending, updated_at: '2026-09-12T00:00:00Z' }]))).mockResolvedValueOnce(new Response('[]')); const r = response(); await handler({ method: 'POST', body: { action: 'included', jobId: 'j', expectedVisitId: 'j:visit:2', reason: 'Covered' } } as never, r as never); expect(r.status).toHaveBeenCalledWith(409); expect(String(f.mock.calls[2][0])).toContain('updated_at=eq.'); });
  it('rejects stale visit approval', async () => { vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(new Response('[{"role":"admin"}]')).mockResolvedValueOnce(new Response(JSON.stringify([{ value: pending, updated_at: 'x' }]))); const r = response(); await handler({ method: 'POST', body: { action: 'included', jobId: 'j', expectedVisitId: 'j:visit:1', reason: 'Covered' } } as never, r as never); expect(r.status).toHaveBeenCalledWith(409); });
});
