// SolarOps UI catalog capture script.
// Walks scripts/ui-screens.manifest.json and writes a full-page PNG per screen,
// then rebuilds UI_SCREEN_CATALOG.md at the repo root with embedded shots.
//
// Pre-login screens (noAuth:true) are captured first in a clean session.
// Authenticated screens are reached by jumping localStorage['solarflow_current_view'].
// Optional `pre` steps run before each shot: {clickText}, {click:selector}, {wait:ms}.
//
// Usage:  node scripts/capture-screens.mjs [--url=http://localhost:5173]
// Creds:  SNAP_UI_EMAIL / SNAP_UI_PASSWORD from .env.local (gitignored).
// Engine behind the /snap-ui command and the post-deploy refresh.

import { chromium } from 'playwright';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..', '..');
const appDir = resolve(__dirname, '..');
const argUrl = process.argv.find(a => a.startsWith('--url='));
const BASE_URL = argUrl ? argUrl.split('=')[1] : (process.env.SNAP_UI_URL || 'http://localhost:5173');

function readEnvLocal() {
  const out = {};
  const p = join(appDir, '.env.local');
  if (!existsSync(p)) return out;
  for (const line of readFileSync(p, 'utf8').split('\n')) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}
const env = { ...readEnvLocal(), ...process.env };
const EMAIL = env.SNAP_UI_EMAIL;
const PASSWORD = env.SNAP_UI_PASSWORD;
if (!EMAIL || !PASSWORD) {
  console.error('Missing SNAP_UI_EMAIL / SNAP_UI_PASSWORD in .env.local');
  process.exit(1);
}

const manifest = JSON.parse(readFileSync(join(__dirname, 'ui-screens.manifest.json'), 'utf8'));
const vp = manifest.viewport || { width: 1440, height: 900 };
const screens = manifest.screens;
const screensDir = join(repoRoot, 'ui-catalog', 'screens');

const GROUPS = [
  { key: 'auth',       title: 'Authentication & Onboarding' },
  { key: 'admin',      title: 'Staff App (admin role)' },
  { key: 'sales',      title: 'Sales Role' },
  { key: 'contractor', title: 'Contractor Portal' },
  { key: 'modal',      title: 'Modals & Drill-down Panels' },
];

const sleep = (ms) => new Promise(r => setTimeout(r, ms));

async function runPre(page, pre) {
  for (const step of pre || []) {
    if (step.wait) { await sleep(step.wait); continue; }
    if (step.clickText) {
      const el = page.getByText(step.clickText, { exact: false }).first();
      await el.click({ timeout: 8000 }).catch(() => console.warn(`    pre clickText "${step.clickText}" not found`));
    } else if (step.click) {
      await page.locator(step.click).first().click({ timeout: 8000 })
        .catch(() => console.warn(`    pre click "${step.click}" not found`));
    }
  }
}

function relPath(screen) {
  return join('ui-catalog', 'screens', screen.group, `${screen.id}.png`).split('\\').join('/');
}

async function shoot(page, screen) {
  const dir = join(screensDir, screen.group);
  mkdirSync(dir, { recursive: true });
  await sleep(1200);
  await runPre(page, screen.pre);
  await page.screenshot({ path: join(dir, `${screen.id}.png`), fullPage: true });
  console.log(`  captured ${screen.group}/${screen.id}`);
  return relPath(screen);
}

async function login(page) {
  await page.goto(BASE_URL, { waitUntil: 'domcontentloaded' });
  await page.waitForSelector('input[type="email"]', { timeout: 30000 });
  await page.fill('input[type="email"]', EMAIL);
  await page.fill('input[type="password"]', PASSWORD);
  await page.click('button[type="submit"]');
  await page.waitForSelector('nav, [class*="sidebar"], aside', { timeout: 30000 });
  await sleep(2500);
}

function buildCatalog(results) {
  const now = new Date().toISOString().slice(0, 10);
  const ok = results.filter(r => r.path).length;
  let md = `# SolarOps - UI Screen Catalog (Visual)\n\n`;
  md += `> Live visual map. Auto-generated by \`solarflow-dashboard/scripts/capture-screens.mjs\` (run via \`/snap-ui\` or on deploy). Do not hand-edit screenshots; edit \`scripts/ui-screens.manifest.json\` and re-run.\n\n`;
  md += `_Last captured: ${now} - ${ok}/${results.length} screens - viewport ${vp.width}x${vp.height}_\n\n`;
  md += `Text-only routing reference: [UI_UX_SCREEN_MAP.md](UI_UX_SCREEN_MAP.md)\n\n`;
  md += `## Contents\n\n`;
  for (const g of GROUPS) {
    const items = results.filter(r => r.group === g.key);
    if (!items.length) continue;
    md += `- **${g.title}**: ` + items.map(r => `[${r.title}](#${r.id})`).join(' / ') + `\n`;
  }
  md += `\n---\n\n`;
  for (const g of GROUPS) {
    const items = results.filter(r => r.group === g.key);
    if (!items.length) continue;
    md += `# ${g.title}\n\n`;
    for (const r of items) {
      md += `## ${r.title}\n\n`;
      md += `<a id="${r.id}"></a>\n\n`;
      md += `- **id:** \`${r.id}\`${r.view ? ` (view \`${r.view}\`)` : r.noAuth ? ' (pre-login)' : ''}\n`;
      md += `- **Macro:** ${r.macro}\n`;
      md += `- **Detail:** ${r.detail}\n\n`;
      if (r.path) md += `![${r.title}](${r.path})\n\n`;
      else md += `_(capture failed: ${r.error || 'unknown'})_\n\n`;
      md += `---\n\n`;
    }
  }
  writeFileSync(join(repoRoot, 'UI_SCREEN_CATALOG.md'), md);
  console.log(`\nCatalog written: UI_SCREEN_CATALOG.md (${ok}/${results.length})`);
}

(async () => {
  const browser = await chromium.launch();
  const results = [];

  const authScreens = screens.filter(s => s.noAuth);
  const appScreens = screens.filter(s => !s.noAuth);

  try {
    // 1) Pre-login screens, in their own throwaway context (these mutate
    //    localStorage/sessionStorage, e.g. contractor mode flags).
    if (authScreens.length) {
      console.log(`Capturing ${authScreens.length} pre-login screens ...`);
      const authCtx = await browser.newContext({ viewport: vp });
      const authPage = await authCtx.newPage();
      authPage.setDefaultTimeout(30000);
      for (const screen of authScreens) {
        try {
          const q = screen.open?.query ? `?${screen.open.query}` : '';
          const path = screen.open?.path || '/';
          await authPage.goto(`${BASE_URL}${path}${q}`, { waitUntil: 'networkidle' });
          results.push({ ...screen, path: await shoot(authPage, screen) });
        } catch (e) {
          console.error(`  FAILED ${screen.id}: ${e.message}`);
          results.push({ ...screen, error: e.message });
        }
      }
      await authCtx.close();
    }

    // 2) Fresh context for the authenticated walk (clean storage = reliable login).
    const ctx = await browser.newContext({ viewport: vp });
    const page = await ctx.newPage();
    page.setDefaultTimeout(30000);
    console.log(`Logging in as ${EMAIL} ...`);
    await login(page);
    console.log(`Capturing ${appScreens.length} authenticated screens ...`);
    for (const screen of appScreens) {
      try {
        await page.evaluate((id) => localStorage.setItem('solarflow_current_view', id), screen.view);
        await page.reload({ waitUntil: 'networkidle' });
        await sleep(1500);
        results.push({ ...screen, path: await shoot(page, screen) });
      } catch (e) {
        console.error(`  FAILED ${screen.id}: ${e.message}`);
        results.push({ ...screen, error: e.message });
      }
    }
    await ctx.close();
  } finally {
    await browser.close();
  }

  // Preserve manifest order in the catalog.
  const ordered = screens.map(s => results.find(r => r.id === s.id)).filter(Boolean);
  buildCatalog(ordered);
  const ok = ordered.filter(r => r.path).length;
  console.log(`Done: ${ok}/${ordered.length} captured.`);
  process.exit(ok === ordered.length ? 0 : 1);
})();
