#!/usr/bin/env python3
"""
Convert merged_customers.json → TypeScript array for dataStore.ts
"""
import json, sys

with open('/Users/cex/SolarOps÷/scripts/merged_customers.json') as f:
    customers = json.load(f)

lines = []
lines.append('// Merged customer database — generated by scripts/merge_customers.py')
lines.append('// Sources: fl_sites.csv + Google Sheet O&M list + importedClients')
lines.append('// DO NOT EDIT MANUALLY — re-run scripts/merge_customers.py to regenerate')
lines.append('const mergedCustomerData = [')

for c in customers:
    addr = c['address'].replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
    name = c['name'].replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
    notes = c['notes'].replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${').replace('\n', '\\n')
    email = c['email'].replace('\\', '\\\\')
    phone = c['phone'].replace('\\', '\\\\')
    lines.append('  {')
    lines.append(f"    clientId: '{c['clientId']}',")
    lines.append(f"    name: {json.dumps(name)},")
    lines.append(f"    email: {json.dumps(email)},")
    lines.append(f"    phone: {json.dumps(phone)},")
    lines.append(f"    address: {json.dumps(c['address'])},")
    lines.append(f"    city: {json.dumps(c['city'])},")
    lines.append(f"    state: {json.dumps(c['state'] or 'FL')},")
    lines.append(f"    zip: {json.dumps(c['zip'])},")
    lines.append(f"    type: '{c['type']}',")
    lines.append(f"    clientStatus: '{c['clientStatus']}',")
    lines.append(f"    solarEdgeSiteId: {json.dumps(c['solarEdgeSiteId'])},")
    lines.append(f"    systemType: {json.dumps(c['systemType'])},")
    lines.append(f"    notes: {json.dumps(c['notes'])},")
    lines.append(f"    installDate: {json.dumps(c['installDate'])},")
    lines.append(f"    peakPower: {c['peakPower']},")
    lines.append(f"    isPowerCare: {'true' if c['isPowerCare'] else 'false'},")
    if c.get('flagged'):
        lines.append(f"    flagged: true,")
    lines.append('  },')

lines.append('] as const;')
lines.append('')
lines.append('export { mergedCustomerData };')

print('\n'.join(lines))
