// SolarFlow MVP - Data Store with LocalStorage + Neon sync
import { AppState, Customer, Job, User, XeroConfig, ClientStatus, CustomerCategory } from '../types';
import { mergedCustomerData } from './mergedCustomers';
import { dbSet } from './db';

const STORAGE_KEY = 'solarflow_data';
const DATA_VERSION = '2026-03-31-powercare-import-v1'; // bump this to force cache clear
const VERSION_KEY = 'solarflow_data_version';

// ── LEGACY ARRAYS REMOVED ── replaced by mergedCustomerData from mergedCustomers.ts
// (generated by scripts/merge_customers.py — sources: fl_sites.csv + Google Sheet + importedClients)

const generateDemoData = (): AppState => {
  // Users are fetched from Supabase after login — not hardcoded here
  const demoUsers: User[] = [
    {
      id: 'user-mia-lopez',
      name: 'Mia Lopez',
      email: 'mia.lopez@conexsol.us',
      phone: '',
      role: 'sales',
      active: true,
      username: 'mialopez',
    },
  ];

  // Build customers from merged dataset (fl_sites.csv + Google Sheet + importedClients)
  const demoCustomers: Customer[] = mergedCustomerData.map((c, index) => ({
    id: `cust-${index + 1}`,
    clientId: c.clientId,
    name: c.name,
    email: c.email,
    phone: c.phone,
    address: c.address,
    city: c.city,
    state: c.state || 'FL',
    zip: c.zip,
    type: c.type as 'residential' | 'commercial',
    category: ((c as any).solarEdgeSiteId ? 'O&M' : undefined) as CustomerCategory | undefined,
    clientStatus: c.clientStatus as ClientStatus,
    createdAt: c.installDate ? new Date(c.installDate).toISOString() : new Date().toISOString(),
    notes: c.notes,
    referralSource: '',
    howFound: '',
    isPowerCare: c.isPowerCare,
    powerCareCaseNumber: (c as any).powerCareCaseNumber || undefined,
    powerCareTrackingNumber: (c as any).powerCareTrackingNumber || undefined,
    solarEdgeSiteId: (c as any).solarEdgeSiteId || undefined,
    systemType: c.systemType as any || undefined,
    trelloBackupUrl: undefined,
  }));

  const today = new Date();
  const yesterday = new Date(today);
  yesterday.setDate(yesterday.getDate() - 1);
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);

  // No demo jobs - imported clients don't have associated jobs yet
  const demoJobs: Job[] = [];

  // Sample notifications for testing
  const demoNotifications = [
    {
      id: 'notif-1',
      userId: 'user-1',
      type: 'contractor_completed' as const,
      title: 'Work Order Completed',
      message: 'Contractor has marked work order WO-2603-00123 as completed',
      read: false,
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'notif-2',
      userId: 'user-1',
      type: 'late_fee_1' as const,
      title: 'Payment Due Soon',
      message: 'Invoice INV-001 is due in 3 days',
      read: false,
      createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'notif-3',
      userId: 'user-1',
      type: 'service_disconnect' as const,
      title: 'Service Update',
      message: 'System maintenance scheduled for 2026-04-20 at 2:00 AM',
      read: true,
      createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    },
  ];

  return {
    users: demoUsers,
    customers: demoCustomers,
    jobs: demoJobs,
    xeroConfig: {
      connected: false,
    },
    solarEdgeConfig: {
      apiKey: '',
    },
    currentUser: undefined as any,
    notifications: demoNotifications,
  };
};

export const loadData = (): AppState => {
  try {
    // If data version changed (new import), wipe the old customer cache
    const storedVersion = localStorage.getItem(VERSION_KEY);
    if (storedVersion !== DATA_VERSION) {
      localStorage.removeItem(STORAGE_KEY);
      localStorage.setItem(VERSION_KEY, DATA_VERSION);
    }

    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      const parsed = JSON.parse(stored);
      const freshData = generateDemoData();
      const storedSolarEdgeConfig = parsed.solarEdgeConfig || {};
      const apiKey = storedSolarEdgeConfig.apiKey?.trim() ?? '';

      // If stored customers exist, use them (preserves deletes/edits/adds).
      // Otherwise fall back to freshly imported data.
      const customers = Array.isArray(parsed.customers) && parsed.customers.length > 0
        ? parsed.customers
        : freshData.customers;

      return {
        ...freshData,
        ...parsed,
        customers,
        notifications: Array.isArray(parsed.notifications) ? parsed.notifications : [],
        solarEdgeExtraSites: Array.isArray(parsed.solarEdgeExtraSites) ? parsed.solarEdgeExtraSites : [],
        solarEdgeConfig: {
          apiKey: apiKey,
          lastSync: storedSolarEdgeConfig.lastSync,
          siteCount: storedSolarEdgeConfig.siteCount,
          nextSyncAllowed: storedSolarEdgeConfig.nextSyncAllowed,
          dailyCallCount: storedSolarEdgeConfig.dailyCallCount,
          dailyCallDate: storedSolarEdgeConfig.dailyCallDate,
        },
      };
    }
  } catch (e) {
    console.error('Failed to load data:', e);
  }
  return generateDemoData();
};

export const saveData = (state: AppState): void => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    dbSet(STORAGE_KEY, state);
  } catch (e) {
    console.error('Failed to save data:', e);
  }
};

export const clearData = (): void => {
  localStorage.removeItem(STORAGE_KEY);
};
