// Auto-generated from SolarEdge API — do not edit manually
// Conexsol Florida Group | 191 sites | Fetched live
export interface SolarEdgeSite {
  siteId: string;
  clientId: string;
  siteName: string;
  address: string;
  status: string;
  peakPower: number;
  installDate: string;
  ptoDate: string;
  alerts: number;
  highestImpact: string;
  systemType: string;
  module: string;
  todayKwh: number;
  monthKwh: number;
  yearKwh: number;
  lifetimeKwh: number;
  lastUpdate: string;
}

export const FL_SITES: SolarEdgeSite[] = [
  {
    "siteId": "1879754",
    "clientId": "",
    "siteName": "City of Tamarac Firestation 36",
    "address": "Northwest 72nd Street 7499, Tamarac, FL, 33321",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-08-05",
    "ptoDate": "",
    "alerts": 11,
    "highestImpact": "5",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3822044",
    "clientId": "",
    "siteName": "DELETE FL",
    "address": "Southwest 68th Street 7400, Glenvar Heights, FL, 33143",
    "status": "Pending",
    "peakPower": 0.0,
    "installDate": "2023-07-27",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1051701",
    "clientId": "",
    "siteName": "Novar, John TSP18070",
    "address": "Southwest 83rd Avenue 13055, Pinecrest, FL, 33156",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-02-05",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2492815",
    "clientId": "",
    "siteName": "US-15015",
    "address": "Northwest 52nd Street 2081, Kings Point, FL, 33496",
    "status": "Pending",
    "peakPower": 0.0,
    "installDate": "2021-10-01",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1893574",
    "clientId": "",
    "siteName": "US-15017 Parque Solar Doral",
    "address": "Northwest 78th Avenue 3500, Virginia Gardens, FL, 33122",
    "status": "Pending",
    "peakPower": 0.0,
    "installDate": "2020-11-03",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1991357",
    "clientId": "",
    "siteName": "US-15019",
    "address": "Alcazar Avenue 395, Coral Gables, FL, 33134",
    "status": "Pending",
    "peakPower": 0.0,
    "installDate": "2020-12-22",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3151049",
    "clientId": "",
    "siteName": "US-15036 Res Bobby Acon",
    "address": "Northwest 100th Avenue 2700, Doral, FL, 33172",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-09-28",
    "ptoDate": "",
    "alerts": 3,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2933092",
    "clientId": "",
    "siteName": "US 15054 Residence Rosales Coral Gable",
    "address": "Palermo Avenue 928, Coral Gables, FL, 33134",
    "status": "Pending",
    "peakPower": 0.0,
    "installDate": "2022-06-03",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3821377",
    "clientId": "",
    "siteName": "US-15057 Fonte Residence",
    "address": "7400 SW 68th Street, Glenvar Heights, FL, 33143",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-07-27",
    "ptoDate": "",
    "alerts": 3,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4040407",
    "clientId": "",
    "siteName": "US-15068 Pelaez Residence",
    "address": "Country Club Lane 3995, Oakland Park, FL, 33308",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-11-22",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3874712",
    "clientId": "",
    "siteName": "US-15086 Korda Residence",
    "address": "Northeast 12th Place 1515, Miami, FL, 33139",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-08-25",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3778884",
    "clientId": "",
    "siteName": "US-15101 Ciampi Residence",
    "address": "Montclaire Drive 149, Weston, FL, 33326",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-12-01",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1094489",
    "clientId": "",
    "siteName": "US-15175 Pablo Herrera",
    "address": "Southwest 23rd Street 2305, Coral Gables, FL, 33145",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-03-05",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2265412",
    "clientId": "",
    "siteName": "US-15190 Paredes Manuel",
    "address": "Southwest 122nd Court 13978, Three Lakes, FL, 33186",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-04-27",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "912113",
    "clientId": "",
    "siteName": "US-15193 David Gonzalez",
    "address": "Misty Oaks Circle 2724, Royal Palm Beach, FL, 33411",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-11-11",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3012235",
    "clientId": "",
    "siteName": "US-15194 Lucas Varela-Cid",
    "address": "Northeast 5th Avenue 15391, Golden Glades, FL, 33162",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-05-10",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2911143",
    "clientId": "",
    "siteName": "US-15196 Sean Paquet",
    "address": "Southwest 111th Avenue 16423, Palmetto Estates, FL, 33157",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-01-28",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "198866",
    "clientId": "",
    "siteName": "US-15197 Island Hammock Pet Hospital",
    "address": "98175 Overseas Highway , Key Largo, FL, 33037",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2015-12-14",
    "ptoDate": "",
    "alerts": 21,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3514539",
    "clientId": "",
    "siteName": "US-15198 Juan Recio",
    "address": "Aqua Court 10711, Parkland, FL, 33076",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-12-05",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3334347",
    "clientId": "",
    "siteName": "US-15200 Clarance Harris",
    "address": "Northwest 24th Avenue 13310, Opa-locka, FL, 33167",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-10-02",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "5",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4429124",
    "clientId": "",
    "siteName": "US-15204 Juan Alassia",
    "address": "Bay Heights Drive 20, Miami, FL, 33133",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2024-10-08",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1466122",
    "clientId": "",
    "siteName": "US-15206 Daniel Rey",
    "address": "Northwest 20th Court 10330, Plantation, FL, 33322",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-01-23",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1080967",
    "clientId": "",
    "siteName": "US-15207 Marco Oliveira",
    "address": "Southwest 133rd Terrace, 6700, Pinecrest, FL, 33156",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-04-19",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "533422",
    "clientId": "",
    "siteName": "US-15208 Azad Amin",
    "address": "Lauderdale Manor Drive 1753, Rock Island, FL, 33311",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2017-09-05",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2907284",
    "clientId": "",
    "siteName": "US-15210 Ramon Gutierrez",
    "address": "Southwest 159th Terrace 11014, Palmetto Estates, FL, 33157",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-03-28",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2979061",
    "clientId": "",
    "siteName": "US-15213 Walumbwa, Ochieng",
    "address": "Southwest 179th Street 8521, East Perrine, FL, 33157",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-02-25",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "291002",
    "clientId": "",
    "siteName": "US-15214 Alexey Alonso",
    "address": "19120 NW 10th Street , Southwest Ranches, FL, 33029",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2016-06-27",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3602247",
    "clientId": "",
    "siteName": "US-15215 Jeeyoung Kim",
    "address": "Funston Street 1418, Hollywood, FL, 33020",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-06-14",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "880643",
    "clientId": "",
    "siteName": "US-15216 Yadiel Huet",
    "address": "6081 SW 153 Court Road , Kendale Lakes, FL, 33193",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-10-23",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4151683",
    "clientId": "",
    "siteName": "US-15217 Donald Said",
    "address": "Northwest 26th Drive 11090, Coral Springs, FL, 33065",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2024-01-25",
    "ptoDate": "",
    "alerts": 21,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3927343",
    "clientId": "",
    "siteName": "US-15218 Darryl Leversuch",
    "address": "Northwest 15th Street 10862, Coral Springs, FL, 33071",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-05-09",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1586005",
    "clientId": "",
    "siteName": "US-15219 Jessica Valenzuela",
    "address": "Dynasty Drive 8407, Sandalfoot Cove, FL, 33433",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-04-20",
    "ptoDate": "",
    "alerts": 4,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1202725",
    "clientId": "",
    "siteName": "US-15222 Francisco Maldonado",
    "address": "Dinner Lake Avenue 141, Waverly, FL, 33859",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-06-18",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "1",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3092553",
    "clientId": "",
    "siteName": "US-15223 Thomas Mcleod",
    "address": "Southwest 44th Terrace 5990, Coral Terrace, FL, 33155",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-05-31",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3592758",
    "clientId": "",
    "siteName": "US-15226 Regla Glau",
    "address": "Southwest 302nd Street 15370, Leisure City, FL, 33033",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-08-04",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "767705",
    "clientId": "",
    "siteName": "US-15227 Joshua McGehee",
    "address": "11683 46th Place North, Royal Palm Beach, FL, 33411",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-06-22",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "913858",
    "clientId": "",
    "siteName": "US-15228 William Rolack",
    "address": "Long Acre Drive 8461, Lake Lucerne, FL, 33025",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-10-16",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "657747",
    "clientId": "",
    "siteName": "US-15229 Gary McMillan",
    "address": "Allamanda Street 3255, Coral Gables, FL, 33133",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-03-02",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1699709",
    "clientId": "",
    "siteName": "US-15230 Dorine Wollangk",
    "address": "Northeast 26th Avenue 954, Terra Mar, FL, 33062",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-07-07",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1504435",
    "clientId": "",
    "siteName": "US-15233 David Smitherman",
    "address": "Northwest 112th Street 570, Pinewood, FL, 33168",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-10-10",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "883536",
    "clientId": "",
    "siteName": "US-15234 Robert Moch",
    "address": "7770 NW 47th St, Tamarac, FL, 33351",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-10-25",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "1",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "813738",
    "clientId": "",
    "siteName": "US-15235 Freída Rosario",
    "address": "Royal Palm Beach Boulevard 4840, Royal Palm Beach, FL, 33411",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-05-09",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "5",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "874172",
    "clientId": "",
    "siteName": "US-15236 Tara Batz",
    "address": "Country Cottage Lane, 240, Winter Garden, FL, 34787",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-10-17",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2677385",
    "clientId": "",
    "siteName": "US-15238 Yamile Camejo",
    "address": "Southwest 69th Avenue 1366, Coral Terrace, FL, 33144",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-01-12",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1255465",
    "clientId": "",
    "siteName": "US-15240 Anthony Gandley",
    "address": "Bishop Landing Way 3785, Meadow Woods, FL, 32824",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-08-29",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1144936",
    "clientId": "",
    "siteName": "US-15242 Ernesto Catala",
    "address": "402 South Jefferson Street , Beverly Hills, FL, 34465",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-04-08",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3175522",
    "clientId": "",
    "siteName": "US-15243 Yosvani Camargo",
    "address": "Southwest 154th Court 1379, Tamiami, FL, 33194",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-08-04",
    "ptoDate": "",
    "alerts": 9,
    "highestImpact": "1",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3606676",
    "clientId": "",
    "siteName": "US-15244 Carolys Rivera",
    "address": "Majestic Lane 1529, Wahneta, FL, 33880",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-03-30",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1524195",
    "clientId": "",
    "siteName": "US-15245 Cristiano Sanches-Rodrigues",
    "address": "Lake Park Circle North 8981, Pine Island Ridge, FL, 33328",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-03-24",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "1",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "514479",
    "clientId": "",
    "siteName": "US-15246 John Pirroni",
    "address": "3230 Northeast 40th Street, Lauderdale-by-the-Sea, FL, 33308",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2017-08-04",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1106221",
    "clientId": "",
    "siteName": "US-15247 Anniel Romero",
    "address": "Burlington Street, 731, Opa-locka, FL, 33054",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-05-10",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1217797",
    "clientId": "",
    "siteName": "US-15248 Jeremy Fisher",
    "address": "Alhambra Boulevard 7721, Miramar, FL, 33023",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-03-25",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4016590",
    "clientId": "",
    "siteName": "US-15253 Jorge Bravo",
    "address": "Northwest 15th Court 8631, Cooper City, FL, 33024",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-08-25",
    "ptoDate": "",
    "alerts": 3,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2339903",
    "clientId": "",
    "siteName": "US-15256 Kyle LaCroix",
    "address": "Surrey Drive 2579, Palm Harbor, FL, 34684",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-06-25",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3334934",
    "clientId": "",
    "siteName": "US-15259 Miguel Vargas",
    "address": "Porter Road 14548, Bay Lake, FL, 34787",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-08-02",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "740778",
    "clientId": "",
    "siteName": "US-15260 Luisking Pena",
    "address": "Northwest 53rd Court 10246, Coral Springs, FL, 33076",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-06-03",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1830725",
    "clientId": "",
    "siteName": "US-15272 Tino Garcia",
    "address": "406 Galloway Street , Lake Alfred, FL, 33850",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-09-18",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3185499",
    "clientId": "",
    "siteName": "US-15273 Gabriel Gareis",
    "address": "Northwest 149th Street 1050, Golden Glades, FL, 33168",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-06-20",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2788011",
    "clientId": "",
    "siteName": "US-15274 Joaquín Molina",
    "address": "Lobelia Drive 408, Davenport, FL, 33837",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-02-08",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "515771",
    "clientId": "",
    "siteName": "US-15276 Pedro Olavarria",
    "address": "Horse Creek Lane 2031, Davenport, FL, 33844",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2017-08-08",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1593529",
    "clientId": "",
    "siteName": "US-15279 Ivan Rodríguez",
    "address": "Haines Drive 1210, Lake Alfred, FL, 33881",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-03-23",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2601416",
    "clientId": "",
    "siteName": "US-15285 Roselore Edouard",
    "address": "Bravada Street 354, Ocoee, FL, 34761",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-10-28",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2800067",
    "clientId": "",
    "siteName": "US-15287 Germitha Hora",
    "address": "Northwest 28th Street 6461, Lauderdale Lakes, FL, 33313",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-02-02",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3369430",
    "clientId": "",
    "siteName": "US-15288 Maritza Garcia",
    "address": "Southwest 149th Avenue 5853, Kendale Lakes, FL, 33193",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-09-20",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "300242",
    "clientId": "",
    "siteName": "US-15289 James Ward",
    "address": "Wilkinson Road 590, Hypoluxo, FL, 33462",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2016-07-20",
    "ptoDate": "",
    "alerts": 3,
    "highestImpact": "5",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "455865",
    "clientId": "",
    "siteName": "US-15290 Omar Resto",
    "address": "West Hamilton Avenue 9007, Town 'n' Country, FL, 33615",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2017-04-27",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3349192",
    "clientId": "",
    "siteName": "US-15291 Barrea, William",
    "address": "Northeast 155th Street 1145, North Miami Beach, FL, 33162",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-04-27",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1024878",
    "clientId": "",
    "siteName": "US-15291 Lellany Guevara",
    "address": "15270 Southwest 41st Terrace, Kendale Lakes, FL, 33185",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-03-05",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "103050",
    "clientId": "",
    "siteName": "US-15292 ManishPV",
    "address": "E Cherry Lake Dr 14371, Palm Valley, FL, 32258",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2015-02-18",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "490551",
    "clientId": "",
    "siteName": "US-15293 Arlene Malloch",
    "address": "3910 Lake Drive Ext, Delray Beach, FL, 33435",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2017-06-27",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3230026",
    "clientId": "",
    "siteName": "US-15294 Bruno Dominijanni",
    "address": "Longmeadow Circle 9384, Boynton Beach, FL, 33436",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-02-12",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3125493",
    "clientId": "",
    "siteName": "US-15295 Julio Gómez",
    "address": "Southwest 191st Street 8190, Lakes by the Bay, FL, 33157",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-09-13",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "660462",
    "clientId": "",
    "siteName": "US-15297 Carlos Pineda",
    "address": "312 Southwest 2nd Street, Hallandale Beach, FL, 33009",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-03-08",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3777860",
    "clientId": "",
    "siteName": "US-15298 Charlie Roldan",
    "address": "Bass Boat Way 3125, Campbell, FL, 34746",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-03-14",
    "ptoDate": "",
    "alerts": 8,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4827180",
    "clientId": "",
    "siteName": "US-15299 Marcus Haynes",
    "address": "Belsfield Circle 2238, Clermont, FL, 34711",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2026-02-19",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "464346",
    "clientId": "",
    "siteName": "US-15302 Junior Rodríguez (Jacksonville)",
    "address": "Paul Bett Drive 5520, Jacksonville, FL, 32277",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2017-05-09",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1014826",
    "clientId": "",
    "siteName": "US-15306 Ian Brown",
    "address": "Northwest 28th Manor 10621, Tamarac, FL, 33322",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-02-26",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "483575",
    "clientId": "",
    "siteName": "US-15310 Evelyn and Joangel Gonzalez",
    "address": "4301 Washington Street, Carver Ranches, FL, 33021",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2017-06-15",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3508416",
    "clientId": "",
    "siteName": "US-15311 Jesús Soto",
    "address": "Barberry Drive 1531, Kissimmee, FL, 34744",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-02-12",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3294301",
    "clientId": "",
    "siteName": "US-15312 Jerry Hesselman",
    "address": "Bluff Oak Loop 4420, Campbell, FL, 34746",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-11-28",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2883230",
    "clientId": "",
    "siteName": "US-15313 Leonard Johnson",
    "address": "Satin Lily Drive 13206, Boyette, FL, 33579",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-05-25",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2819723",
    "clientId": "",
    "siteName": "US-15314 Iris Aponte",
    "address": "Lake Smart Circle 276, Lake Alfred, FL, 33881",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-03-08",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3654063",
    "clientId": "",
    "siteName": "US-15315 Clara Fana",
    "address": "Northwest 27th Street 6704, Margate, FL, 33063",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-04-11",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "643657",
    "clientId": "",
    "siteName": "US-15316 Eric Morales",
    "address": "Summerfield Circle, 4720, Cypress Gardens, FL, 33881",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-02-12",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4620406",
    "clientId": "",
    "siteName": "US-15317 Gemhson Villarson",
    "address": "Delancey Drive 739, Davenport, FL, 33837",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2024-05-13",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3722620",
    "clientId": "",
    "siteName": "US-15318 Rick Hackbarth",
    "address": "Grove Street 456, De Leon Springs, FL, 32720",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-12-27",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3185518",
    "clientId": "",
    "siteName": "US-15320 Ana Henriquez",
    "address": "Northwest 195th Terrace 5682, Country Club, FL, 33055",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-06-11",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4680814",
    "clientId": "",
    "siteName": "US-15321 Cleverton Possani",
    "address": "Knoll Tree Lane 439, Forest City, FL, 32712",
    "status": "Pending",
    "peakPower": 0.0,
    "installDate": "2025-07-22",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2349689",
    "clientId": "",
    "siteName": "US-15323 Yongxin Guo",
    "address": "Clubhouse Estates Drive 7627, Doctor Phillips, FL, 32819",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-08-27",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2827287",
    "clientId": "",
    "siteName": "US-15325 Donald Byrd",
    "address": "Henderson Street 954, Deltona, FL, 32725",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-02-09",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "188878",
    "clientId": "",
    "siteName": "US-15326 Alejandro Vallera",
    "address": "1200 S Alhambra Cir, South Miami, FL, 33146",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2015-11-13",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1868331",
    "clientId": "",
    "siteName": "US-15328 Waren Lantigua",
    "address": "Lake Lucerne Way 327, Lake Alfred, FL, 33881",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-10-13",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "847816",
    "clientId": "",
    "siteName": "US-15330 Cheryl Duncan",
    "address": "Minnesota Street 514, Lantana, FL, 33462",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-05-11",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "5",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3498902",
    "clientId": "",
    "siteName": "US-15331 Karen Savadge",
    "address": "Hoffner Avenue 2911, Pine Castle, FL, 32812",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-07-28",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4692910",
    "clientId": "",
    "siteName": "US-15332 Eduardo Echagarruga",
    "address": "Southwest 146th Street 13245, Three Lakes, FL, 33186",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2025-08-06",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1709610",
    "clientId": "",
    "siteName": "US-15333 John Santos",
    "address": "Thomas Jefferson Circle West 7225, Wahneta, FL, 33830",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-07-09",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3051916",
    "clientId": "",
    "siteName": "US-15337 Virginia Cumberbatch",
    "address": "Northwest 11th Court 1600, Washington Park, FL, 33311",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-08-08",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "671234",
    "clientId": "",
    "siteName": "US-15339 Iki Dugno",
    "address": "8314 Civic Road, Town 'n' Country, FL, 33615",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-03-17",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1235308",
    "clientId": "",
    "siteName": "US-15342 Abed Laracuente",
    "address": "Oak Shore Drive 6187, Saint Cloud, FL, 34771",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-08-14",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4000854",
    "clientId": "",
    "siteName": "US-15344 Edgar Fernandez",
    "address": "835 Northwest 132nd Street, Golden Glades, FL, 33168",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-07-25",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3615945",
    "clientId": "",
    "siteName": "US-15358 Paulino Vieira Neto",
    "address": "Verona Lakes Boulevard 9530, Greenacres City, FL, 33472",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-02-14",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "6",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4357504",
    "clientId": "",
    "siteName": "US-15359 Héctor Escobales",
    "address": "9006 Bana Villa Court, Town 'n' Country, FL, 33635",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2024-08-03",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "960603",
    "clientId": "",
    "siteName": "US-15362 Edgar Vazquez",
    "address": "Zachary Ridge Court 1145, Loughman, FL, 34747",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-01-05",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3925027",
    "clientId": "",
    "siteName": "US-15363 Francisco Perez",
    "address": "Southwest 161st Place 11338, The Hammocks, FL, 33196",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-07-17",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4682784",
    "clientId": "",
    "siteName": "US-15364 Clifford Langston",
    "address": "Elnor Street 609, Plant City, FL, 33563",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2025-01-01",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3210117",
    "clientId": "",
    "siteName": "US-15365 Jim Larrimore",
    "address": "Formby Grande Avenue 113, Daytona Beach, FL, 32124",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-10-20",
    "ptoDate": "",
    "alerts": 7,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3357545",
    "clientId": "",
    "siteName": "US-15366 Rolando Edwards",
    "address": "Maiden Terrace 1037, Celebration, FL, 34747",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-10-13",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "113640",
    "clientId": "",
    "siteName": "US-15367 Sonja Reeves",
    "address": "5525 Jefferson Street, Carver Ranches, FL, 33021",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2015-04-14",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "6",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2392861",
    "clientId": "",
    "siteName": "US-15368 THOMAS TWEIT",
    "address": "Ramblewood Road 10532, Southchase, FL, 32837",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-06-14",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1361894",
    "clientId": "",
    "siteName": "US-15370 Meyer - Killeen",
    "address": "Southwest 147th Avenue 25750, Naranja, FL, 33032",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-11-04",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "458212",
    "clientId": "",
    "siteName": "US-15371 Rachel Hober",
    "address": "Plantation Oak Drive 1929, Meadow Woods, FL, 32824",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2017-05-02",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2875515",
    "clientId": "",
    "siteName": "US-15372 Emily Helbick",
    "address": "Southeast 27th Court 170, Gulf Stream, FL, 33435",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-05-03",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3223848",
    "clientId": "",
    "siteName": "US-15373 Tyler Murphy",
    "address": "Dolce Drive 314, Dundee, FL, 33838",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-09-19",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3358969",
    "clientId": "",
    "siteName": "US-15374 Carole Walker",
    "address": "Dellwood Road 3680, Royal Palm Beach, FL, 33470",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-10-05",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2272438",
    "clientId": "",
    "siteName": "US-15375 Chris Rediske",
    "address": "Pocahontas Path 1750, Maitland, FL, 32751",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-03-24",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2198392",
    "clientId": "",
    "siteName": "US-15376 Patricia Marshall",
    "address": "Irving Bend Drive 358, Mascotte, FL, 34736",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-03-10",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1737038",
    "clientId": "",
    "siteName": "US-15377 Liz Hargis",
    "address": "Avenue F Southeast 706, Winter Haven, FL, 33880",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-07-28",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3304023",
    "clientId": "",
    "siteName": "US-15379 Bracci Residence",
    "address": "Peach Orchard Way 13921, Tildenville, FL, 34787",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-10-11",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4009909",
    "clientId": "",
    "siteName": "US-15380 Juliann Malecot",
    "address": "94th Street North 12055, Largo, FL, 33773",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-03-01",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3331062",
    "clientId": "",
    "siteName": "US-15381 Heriberto Rosario",
    "address": "Cheri Court 1541, Kissimmee, FL, 34744",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-12-07",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "645843",
    "clientId": "",
    "siteName": "US-15383 Diana Parra",
    "address": "414 Largovista Drive, Oakland, FL, 34787",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-02-14",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4694516",
    "clientId": "",
    "siteName": "US-15388 Dorothy Grant",
    "address": "Hawkshead Drive 3657, Minneola, FL, 34711",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2025-08-08",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4823287",
    "clientId": "",
    "siteName": "US-15389-1 Mister 01 (1)",
    "address": "West 26th Street 689, Hialeah, FL, 33010",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2026-02-12",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3981245",
    "clientId": "",
    "siteName": "US-15394 Michael Young",
    "address": "Verwood Way 10, Seminole Manor, FL, 33426",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-10-16",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2568456",
    "clientId": "",
    "siteName": "US-15395 Brian Robertson",
    "address": "Snapper Drive 1873, Poinciana, FL, 34759",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-11-01",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1226193",
    "clientId": "",
    "siteName": "US-15396 Manesh Mohan",
    "address": "Russell Bridge Drive 15097, Fruit Cove, FL, 32259",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-08-08",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "68251",
    "clientId": "",
    "siteName": "US-15397 Jarrod Hollander",
    "address": "13241 Starfish Drive, Hudson, FL, 34667",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2014-07-29",
    "ptoDate": "",
    "alerts": 4,
    "highestImpact": "5",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1040552",
    "clientId": "",
    "siteName": "US-15399 Jesse Foote",
    "address": "Dornich Drive 5780, Polk City, FL, 33823",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-03-19",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2938744",
    "clientId": "",
    "siteName": "US-15400 Bud Laudenslager",
    "address": "Windswept Way 331, Fruit Cove, FL, 32092",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-06-06",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3237302",
    "clientId": "",
    "siteName": "US-15401 Blas Santander",
    "address": "Southwest 24th Avenue 2501, Coral Gables, FL, 33133",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-10-05",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1131486",
    "clientId": "",
    "siteName": "US-15402 Pavel Rizo FL",
    "address": "Grand Island Way, 9238, Bay Lake, FL, 34787",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-05-29",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "5",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2267220",
    "clientId": "",
    "siteName": "US-15403 Austria Díaz",
    "address": "Settlers Creek Loop 8256, Gibsonia, FL, 33810",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-04-28",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "417144",
    "clientId": "",
    "siteName": "US-15405 Amanda Himmler",
    "address": "Whirley Road 16748, Cheval, FL, 33558",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2017-02-16",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2788929",
    "clientId": "",
    "siteName": "US-15406 Chase Laurain",
    "address": "Deerfield Drive 17641, Cheval, FL, 33558",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-01-19",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2697150",
    "clientId": "",
    "siteName": "US-15407 Yaniel del corral",
    "address": "West 79th Street 993, Miami Lakes, FL, 33014",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-01-24",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2002284",
    "clientId": "",
    "siteName": "US-15408 Philip King",
    "address": "Lake Mirror Drive Northwest 1540, Inwood, FL, 33881",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-12-07",
    "ptoDate": "",
    "alerts": 3,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1053376",
    "clientId": "",
    "siteName": "US-15409 Silvio Negron",
    "address": "70 Andora Court , Poinciana, FL, 34758",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-03-29",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1385733",
    "clientId": "",
    "siteName": "US-15411 Lynn Wagner",
    "address": "130 West Welch Road , Apopka, FL, 32712",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-11-18",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1757021",
    "clientId": "",
    "siteName": "US-15412 Khristopher deCapua",
    "address": "16601 Goose Ribbon Pl. , Wimauma, FL, 33598",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-07-03",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2866995",
    "clientId": "",
    "siteName": "US-15414 Tanya Aleman",
    "address": "Tidal Rock Avenue 1015, Ruskin, FL, 33570",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-04-12",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "1",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3310258",
    "clientId": "",
    "siteName": "US-15421 Rafael Padron",
    "address": "Southwest 14th Street 1811, Miami, FL, 33145",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-08-31",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4167778",
    "clientId": "",
    "siteName": "US-15422  Huston Newsome",
    "address": "Challenger Drive 15025, Tavares, FL, 32778",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2024-01-18",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1443054",
    "clientId": "",
    "siteName": "US-15423 Brett Conroy",
    "address": "John Hancock Drive , Lake Butter, FL, 34787",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-12-19",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "436620",
    "clientId": "",
    "siteName": "US-15431 Jeffrey Estevez",
    "address": "West Frierson Avenue 203, Tampa, FL, 33603",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2017-03-17",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2726777",
    "clientId": "",
    "siteName": "US-15435 Jose Tobar",
    "address": "Beulah Road 1330, Winter Garden, FL, 34787",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-02-02",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3170349",
    "clientId": "",
    "siteName": "US-15436 Ashley Halliwell",
    "address": "Wattenberg Court East, 10251, Baldwin, FL, 32221",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-10-03",
    "ptoDate": "",
    "alerts": 3,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3452173",
    "clientId": "",
    "siteName": "US-15437 Christian Tovar",
    "address": "Alba Lane 9008, Citrus Ridge, FL, 34747",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-01-18",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3461374",
    "clientId": "",
    "siteName": "US-15438 Cory Mulinare",
    "address": "74 Northwest 108th Street , Miami Shores, FL, 33168",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-02-06",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1358103",
    "clientId": "",
    "siteName": "US-15439 Yachira Gutierrez",
    "address": "Elm Court 229, Poinciana, FL, 34759",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-10-28",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3729709",
    "clientId": "",
    "siteName": "US-15440 Carlin Doyen",
    "address": "Patrick Henry Road 118, Wahneta, FL, 33830",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-02-02",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1284769",
    "clientId": "",
    "siteName": "US-15441 Georgina Martinez",
    "address": "Sunset Point Circle 12125, Wellington, FL, 33414",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-07-17",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1537938",
    "clientId": "",
    "siteName": "US-15448 John Hinshaw",
    "address": "Cadiz Loop 324, Davenport, FL, 33837",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-03-13",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3847506",
    "clientId": "",
    "siteName": "US-15451 Johanna Danton",
    "address": "Hayes Street 5510, Pembroke Pines, FL, 33021",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-05-22",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1384540",
    "clientId": "",
    "siteName": "US-15454 Nicolas Guerrero",
    "address": "Haulover Drive 819, Wekiwa Springs, FL, 32714",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-10-29",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2762131",
    "clientId": "",
    "siteName": "US-15456 Santos Auli",
    "address": "Comerwood Drive 1386, Deltona, FL, 32738",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-02-21",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "471166",
    "clientId": "",
    "siteName": "US-15461 Richard Falkowski",
    "address": "Calle De Sol 5053, Bay Hill, FL, 32819",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2017-05-24",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1235853",
    "clientId": "",
    "siteName": "US-15464  Judith Martin Dundee FL",
    "address": "Valentina Drive 902, Dundee, FL, 33838",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-08-11",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2269643",
    "clientId": "",
    "siteName": "US-15468 Mary Hannon",
    "address": "Sonia Street 9231, Union Park, FL, 32825",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-05-24",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1932573",
    "clientId": "",
    "siteName": "US-15469 Jonathan Ambaye",
    "address": "Balmoral Drive 925, Loughman, FL, 33896",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-11-18",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2343070",
    "clientId": "",
    "siteName": "US-15470 Arthur Kramer",
    "address": "2057 HEMINGWAY AVE, Haines City, FL, 33844-2401",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-07-06",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4808395",
    "clientId": "",
    "siteName": "US-15471 Dereck Johnson",
    "address": "Chelsea Woods Drive 2919, Bloomingdale, FL, 33596",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2026-01-18",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4817221",
    "clientId": "",
    "siteName": "US-15473 Martin Krauss",
    "address": "Crossing Lane 6435, Gibsonia, FL, 33809",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2026-02-02",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4003521",
    "clientId": "",
    "siteName": "US-15478 Zoila Posada",
    "address": "Hope Lane, 5232, Weeki Wachee, FL, 34606",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-11-21",
    "ptoDate": "",
    "alerts": 3,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3748641",
    "clientId": "",
    "siteName": "US-15479 Kurt Lenz",
    "address": "Bird Song Drive 518, West De Land, FL, 32720",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-01-13",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4797391",
    "clientId": "",
    "siteName": "US-15482 James McClendon",
    "address": "111th Street North 8842, Seminole, FL, 33772",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2025-12-24",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3352794",
    "clientId": "",
    "siteName": "US-15483 David Lautermilch",
    "address": "Hall Road Southeast 3282, Malabar, FL, 32909",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-02-23",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2069819",
    "clientId": "",
    "siteName": "US-15491 Joe Ricketts",
    "address": "Riverport Drive North 2653, Fruit Cove, FL, 32223",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-09-29",
    "ptoDate": "",
    "alerts": 7,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3914500",
    "clientId": "",
    "siteName": "US-15492 Shaykat Ahamed",
    "address": "Southwest 9th Court 5320, Broadview Park, FL, 33317",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-06-29",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3270833",
    "clientId": "",
    "siteName": "US-15499 Tony Perry",
    "address": "Southwest 124th Street 8990, Kendall, FL, 33176",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-08-05",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3069568",
    "clientId": "",
    "siteName": "US-15503 Jason Brunson",
    "address": "Los Arbor Drive 109, North De Land, FL, 32724",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-06-05",
    "ptoDate": "",
    "alerts": 3,
    "highestImpact": "5",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2010041",
    "clientId": "",
    "siteName": "US-15504 N Rodriguez - 16771 Yellow Bluff Rd",
    "address": "Yellow Bluff Road 16771, Yulee, FL, 32226",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-01-05",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "4109951",
    "clientId": "",
    "siteName": "US-15505 Britney W",
    "address": "Southwest 8th Court 7910A, North Lauderdale, FL, 33068",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-12-07",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "510385",
    "clientId": "",
    "siteName": "US-15506 Jonathan Harden",
    "address": "Broken Arrow Drive, 10614, Pebble Creek, FL, 33592",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2017-07-19",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3504967",
    "clientId": "",
    "siteName": "US-15515 Journigan, Steven",
    "address": "Sawmill Court 1188, Goldenrod, FL, 32792",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2023-01-09",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3037874",
    "clientId": "",
    "siteName": "US-15516 Carolina Garcia",
    "address": "352 Creek Road, Lake Alfred, FL, 33850",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-07-27",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1509688",
    "clientId": "",
    "siteName": "US-15517 Bobby Furedi",
    "address": "Northeast 33rd Street 899, Oakland Park, FL, 33334",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-02-21",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "333365",
    "clientId": "",
    "siteName": "US-15518 Brian Daly",
    "address": "Northeast 21st Avenue 2819, Oakland Park, FL, 33306",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2016-11-22",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3542143",
    "clientId": "",
    "siteName": "US-15521 Antonio Marques",
    "address": "South Roundtable Road 15610, Southwest Ranches, FL, 33331",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-10-07",
    "ptoDate": "",
    "alerts": 6,
    "highestImpact": "2",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "760512",
    "clientId": "",
    "siteName": "US-15522 Juan Salazar",
    "address": "Creekside Way 124, Meadow Woods, FL, 32824",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-06-25",
    "ptoDate": "",
    "alerts": 3,
    "highestImpact": "5",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3131378",
    "clientId": "",
    "siteName": "US-15523-1 Charles Roach",
    "address": "16 Sunset Lane, Terra Mar, FL, 33062",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-09-15",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "9",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1473775",
    "clientId": "",
    "siteName": "US-15523-2 Charles Roach",
    "address": "15 Sunset Lane, Terra Mar, FL, 33062",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2020-01-29",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2141371",
    "clientId": "",
    "siteName": "US-15547 Flabio Herrera",
    "address": "Hamlet Loop 421, Loughman, FL, 33837",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2021-02-24",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2811367",
    "clientId": "",
    "siteName": "US-15550 Lee Duerr",
    "address": "North 147 Avenue 3896, Royal Palm Beach, FL, 33470",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-03-30",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2870672",
    "clientId": "",
    "siteName": "US-15551 Brian Olsen",
    "address": "Chatham Circle 1696, South Apopka, FL, 32703",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-03-12",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2962769",
    "clientId": "",
    "siteName": "US-15552 Miller, Stephen",
    "address": "Balboa Lane 6303, Apollo Beach, FL, 33572",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-06-15",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "4",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "754935",
    "clientId": "",
    "siteName": "US-15553 Ronald Green",
    "address": "Northwest 72nd Street, 1370, Gladeview, FL, 33147",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2018-04-02",
    "ptoDate": "",
    "alerts": 3,
    "highestImpact": "5",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "2976098",
    "clientId": "",
    "siteName": "US-15556 José Negron",
    "address": "Landing Drive 24315, Lutz, FL, 33559",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-06-17",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3614623",
    "clientId": "",
    "siteName": "US-15565 Douglas Cline",
    "address": "729 San Raphael St, Poinciana, FL, 34759",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-04-13",
    "ptoDate": "",
    "alerts": 1,
    "highestImpact": "5",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "232625",
    "clientId": "",
    "siteName": "US-15567 Mauricio Vargas - Patricia Morales",
    "address": "11815 Frost Aster Drive, Riverview, FL, 33579",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2016-03-17",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "1119526",
    "clientId": "",
    "siteName": "US-15578 Melvin Mcgill",
    "address": "Granada Avenue, 136, Davenport, FL, 33837",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2019-05-21",
    "ptoDate": "",
    "alerts": 2,
    "highestImpact": "6",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  },
  {
    "siteId": "3456903",
    "clientId": "",
    "siteName": "US-15581 Mikhaylov",
    "address": "Northwest 166th Avenue 1230, Sunshine Ranches, FL, 33028",
    "status": "Active",
    "peakPower": 0.0,
    "installDate": "2022-11-02",
    "ptoDate": "",
    "alerts": 0,
    "highestImpact": "0",
    "systemType": "",
    "module": "",
    "todayKwh": 0.0,
    "monthKwh": 0.0,
    "yearKwh": 0.0,
    "lifetimeKwh": 0.0,
    "lastUpdate": ""
  }
];
